name: Feature Request
description: Submit a feature request
title: "[Feature]: "
labels: ["type: enhancement"]
assignees:
  - thombruce
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit a feature request!
  # - type: input
  #   id: contact
  #   attributes:
  #     label: Contact Details
  #     description: How can we get in touch with you if we need more info?
  #     placeholder: ex. email@example.com
  #   validations:
  #     required: false
  - type: textarea
    id: feature-description
    attributes:
      label: Feature request
      description: Describe the feature you'd like to see.
      placeholder: Tell us about your suggested feature!
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/thombruce/.github/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
