# Electron Build Job; adapted from https://dev.to/erikhofer/build-and-publish-a-multi-platform-electron-app-on-github-3lnd#build
# See that doc for further advice re publishing.
name: Build
on: [push, pull_request]

permissions:
  contents: write

jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/app
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@master
      with:
        node-version: 20
    - name: install dependencies
      run: yarn install
    - name: build
      run: |
        sudo snap install snapcraft --classic
        yarn run electron:build
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_on_mac:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./packages/app
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@master
      with:
        node-version: 20
    - name: install dependencies
      run: yarn install
    - name: build
      run: yarn run electron:build
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_on_win:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./packages/app
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@master
      with:
        node-version: 20
    - name: install dependencies
      run: yarn install --network-timeout 1000000
    - name: build
      run: yarn run electron:build
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
