# Electron Build Job; adapted from https://dev.to/erikhofer/build-and-publish-a-multi-platform-electron-app-on-github-3lnd#build
# See that doc for further advice re publishing.
name: Build
on: [push, pull_request]

jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/app
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@master
      with:
        node-version: 20
    - name: install dependencies
      run: yarn install
    - name: build
      run: yarn run electron:build

  build_on_mac:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./packages/app
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@master
      with:
        node-version: 20
    - name: install dependencies
      run: yarn install
    - name: build
      run: yarn run electron:build

  build_on_win:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./packages/app
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@master
      with:
        node-version: 20
    # See: https://github.com/yarnpkg/yarn/issues/9004#issuecomment-1803643905
    - name: clean cache
      run: yarn cache clean
    - name: delete proxy
      run: yarn config delete proxy
    - name: delete https-proxy
      run: yarn config delete https-proxy
    - name: delete registry
      run: yarn config delete registry
    # /
    - name: install dependencies
      run: yarn install --network-timeout 1000000
    - name: build
      run: yarn run electron:build