# Electron Build Job; adapted from https://dev.to/erikhofer/build-and-publish-a-multi-platform-electron-app-on-github-3lnd#build
# See that doc for further advice re publishing.
name: Build
on: [push, pull_request]

jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@master
      with:
        node-version: 20
    - name: install dependencies
      run: cd packages/app && yarn install
    - name: build
      run: cd packages/app && yarn run electron:build

  build_on_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@master
      with:
        node-version: 20
    - name: install dependencies
      run: cd packages/app && yarn install
    - name: build
      run: cd packages/app && yarn run electron:build

  build_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@master
      with:
        node-version: 20
    - name: install dependencies
      run: cd packages/app && yarn install
    - name: build
      run: cd packages/app && yarn run electron:build