# Simple workflow for deploying static content to GitHub Pages
name: Deploy

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.12"
          cache: yarn

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Restore cache
        uses: actions/cache@v3
        with:
          # CHANGEME: to `packages/web/*` to build the app on GitHub Pages
          path: |
            packages/docs/dist
            packages/docs/.nuxt
          key: ${{ runner.os }}-nuxt-build-${{ hashFiles('packages/docs/dist') }}
          restore-keys: |
            ${{ runner.os }}-nuxt-build-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn lerna run generate # CHANGEME: to `yarn lerna run build` to build the app on GitHub Pages
        env:
          NUXT_APP_BASE_URL: ${{ vars.NUXT_APP_BASE_URL }}
          # VITE_BASE: ${{ vars.TOODLES_BASE }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload dist repository
          path: './packages/docs/dist' # CHANGEME: to `./packages/web/dist` to build the app on GitHub Pages

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
